#if !canImport(ObjectiveC)
  import XCTest

  extension ErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorTests = [
      ("testCardFromCharsThrows", testCardFromCharsThrows),
      ("testCardParseThrows", testCardParseThrows),
      ("testEvaluationDuplicateErrors", testEvaluationDuplicateErrors),
      ("testEvaluationInvalidCountErrors", testEvaluationInvalidCountErrors),
    ]
  }

  extension EvaluationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EvaluationTests = [
      ("testAllFiveCardCombinations", testAllFiveCardCombinations),
      ("testRepresentativeFiveCardHands", testRepresentativeFiveCardHands),
      ("testRepresentativeSevenCardHands", testRepresentativeSevenCardHands),
      ("testRepresentativeSixCardHands", testRepresentativeSixCardHands),
    ]
  }

  extension ExtensionsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExtensionsTests = [
      ("testAllUnique", testAllUnique),
      ("testWrappingPow", testWrappingPow),
    ]
  }

  extension UtilitiesTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UtilitiesTests = [
      ("testBitSequenceGenerator", testBitSequenceGenerator),
      ("testHighRankFromHandBits", testHighRankFromHandBits),
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    [
      testCase(ErrorTests.__allTests__ErrorTests),
      testCase(EvaluationTests.__allTests__EvaluationTests),
      testCase(ExtensionsTests.__allTests__ExtensionsTests),
      testCase(UtilitiesTests.__allTests__UtilitiesTests),
    ]
  }
#endif
